In [1]:
import torch

In [12]:
print(torch.version.__version__)
print(torch.cuda.is_available())
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

2.0.0
True
cuda:0


In [16]:
print(torch.ones(1,3))
print(torch.ones(3))
a = torch.rand(1,3).to(device)
b = torch.ones(3,3).to(device)
print(a)
print(b)
print(a*b)

tensor([[1., 1., 1.]])
tensor([1., 1., 1.])
tensor([[0.4042, 0.6033, 0.7122]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[0.4042, 0.6033, 0.7122],
        [0.4042, 0.6033, 0.7122],
        [0.4042, 0.6033, 0.7122]], device='cuda:0')


True