In [1]:
import torch

In [12]:
print(torch.version.__version__)
print(torch.cuda.is_available())
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

2.0.0
True
cuda:0


In [16]:
print(torch.ones(1,3))
print(torch.ones(3))
a = torch.rand(1,3).to(device)
b = torch.ones(3,3).to(device)
print(a)
print(b)
print(a*b)

tensor([[1., 1., 1.]])
tensor([1., 1., 1.])
tensor([[0.4042, 0.6033, 0.7122]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[0.4042, 0.6033, 0.7122],
        [0.4042, 0.6033, 0.7122],
        [0.4042, 0.6033, 0.7122]], device='cuda:0')


True

In [4]:
import torch.nn as nn
import torch
a = torch.rand(size=(1,3,3))
print(a)
tmp = nn.ConvTranspose2d(1,1,kernel_size=3,stride=2,padding=1,output_padding=1)
print(tmp(a))

tensor([[[0.2850, 0.6127, 0.5854],
         [0.8469, 0.2373, 0.6991],
         [0.1028, 0.4091, 0.7983]]])
tensor([[[ 0.3449,  0.1095,  0.3901,  0.1055,  0.3864,  0.2838],
         [-0.0015,  0.3721,  0.0575,  0.3323, -0.0545,  0.3331],
         [ 0.4224,  0.2022,  0.3384,  0.0851,  0.4020,  0.2795],
         [ 0.0213,  0.2597,  0.1269,  0.4197, -0.1149,  0.3327],
         [ 0.3198,  0.1779,  0.3621,  0.0487,  0.4157,  0.2758],
         [ 0.2744,  0.2387,  0.1812,  0.1455,  0.0628,  0.1923]]],
       grad_fn=<SqueezeBackward1>)
