In [1]:
import torch

In [12]:
print(torch.version.__version__)
print(torch.cuda.is_available())
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

2.0.0
True
cuda:0


In [16]:
print(torch.ones(1,3))
print(torch.ones(3))
a = torch.rand(1,3).to(device)
b = torch.ones(3,3).to(device)
print(a)
print(b)
print(a*b)

tensor([[1., 1., 1.]])
tensor([1., 1., 1.])
tensor([[0.4042, 0.6033, 0.7122]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[0.4042, 0.6033, 0.7122],
        [0.4042, 0.6033, 0.7122],
        [0.4042, 0.6033, 0.7122]], device='cuda:0')


True

In [11]:
import torch.nn as nn
import torch
a = torch.rand(size=(1,3,3))
print(a)
tmp = nn.ConvTranspose2d(1,1,kernel_size=3,stride=2,padding=1,output_padding=1)
print(tmp(a))
import numpy
b = numpy.random.random(size=(2,2))
c = torch.tensor([[b,b],[b,b]])
print(c)
d = torch.tensor([[1,1],[1,1]]).numpy()
print(numpy.array([d,d]))
e = torch.tensor([d,d])
print(e)

tensor([[[0.3324, 0.5671, 0.1196],
         [0.7977, 0.0242, 0.6657],
         [0.2396, 0.1634, 0.2275]]])
tensor([[[-0.0292,  0.1576, -0.0564,  0.0427, -0.0045,  0.0098],
         [ 0.0511, -0.0617, -0.0137, -0.1888,  0.0510, -0.0666],
         [-0.0831,  0.0190,  0.0065,  0.1818, -0.0678,  0.0122],
         [-0.0086, -0.2664,  0.0198,  0.0785, -0.0037, -0.2191],
         [-0.0184,  0.0526, -0.0096,  0.0689, -0.0170,  0.0103],
         [-0.0011, -0.0446,  0.0022, -0.0106, -0.0006, -0.0644]]],
       grad_fn=<SqueezeBackward1>)
tensor([[[[0.4791, 0.2852],
          [0.6839, 0.9076]],

         [[0.4791, 0.2852],
          [0.6839, 0.9076]]],


        [[[0.4791, 0.2852],
          [0.6839, 0.9076]],

         [[0.4791, 0.2852],
          [0.6839, 0.9076]]]], dtype=torch.float64)
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]])


In [27]:
a = torch.tensor([[1,2],[1,2]]).cuda()
print(a)
b = torch.tile(a,(2,3))

tensor([[1, 2],
        [1, 2]], device='cuda:0')
tensor([[1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2]], device='cuda:0')
