In [8]:
import torch

In [9]:
print(torch.version.__version__)
print(torch.cuda.is_available())
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

2.0.0
True
cuda:0


In [10]:
print(torch.ones(1,3))
print(torch.ones(3))
a = torch.rand(1,3).to(device)
b = torch.ones(3,3).to(device)
print(a)
print(b)
print(a*b)

tensor([[1., 1., 1.]])
tensor([1., 1., 1.])
tensor([[0.9220, 0.4005, 0.3144]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[0.9220, 0.4005, 0.3144],
        [0.9220, 0.4005, 0.3144],
        [0.9220, 0.4005, 0.3144]], device='cuda:0')


In [16]:
x = torch.randn(1,3).to(device)
y = torch.ones(3,3).to(device)
z = torch.matmul(x,y)
print(x)
print(y)
print(z)
print(x*y)
print(x@y)
print(x+y)

tensor([[7.5618e-01, 8.9562e-04, 2.1999e+00]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[2.9569, 2.9569, 2.9569]], device='cuda:0')
tensor([[7.5618e-01, 8.9562e-04, 2.1999e+00],
        [7.5618e-01, 8.9562e-04, 2.1999e+00],
        [7.5618e-01, 8.9562e-04, 2.1999e+00]], device='cuda:0')
tensor([[2.9569, 2.9569, 2.9569]], device='cuda:0')
tensor([[1.7562, 1.0009, 3.1999],
        [1.7562, 1.0009, 3.1999],
        [1.7562, 1.0009, 3.1999]], device='cuda:0')


In [52]:
a = torch.tensor([[2.,3.],[3.,4.]])
print(a.shape)
print(a.size)
print(a.data)

torch.Size([2, 2])
<built-in method size of Tensor object at 0x0000017A0598D680>
tensor([[2., 3.],
        [3., 4.]])


In [76]:
b = torch.rand(4,3)
c = torch.rand(2,2,3)
print(b)
print(b.reshape(2,6))
print(c)
print(c.reshape(1,1,12))

tensor([[0.8630, 0.7689, 0.4487],
        [0.6046, 0.0554, 0.2132],
        [0.8916, 0.4259, 0.1259],
        [0.9253, 0.8233, 0.1291]])
tensor([[0.8630, 0.7689, 0.4487, 0.6046, 0.0554, 0.2132],
        [0.8916, 0.4259, 0.1259, 0.9253, 0.8233, 0.1291]])
tensor([[[0.9636, 0.2631, 0.4844],
         [0.6815, 0.4028, 0.4096]],

        [[0.8675, 0.2946, 0.7924],
         [0.1491, 0.6657, 0.9300]]])
tensor([[[0.9636, 0.2631, 0.4844, 0.6815, 0.4028, 0.4096, 0.8675, 0.2946,
          0.7924, 0.1491, 0.6657, 0.9300]]])


In [77]:
print(b[2])
print(b[2,1])
print(b[2][1])

print(c[1])
print(c[1,1])
print(c[1,1,1])

tensor([0.8916, 0.4259, 0.1259])
tensor(0.4259)
tensor(0.4259)
tensor([[0.8675, 0.2946, 0.7924],
        [0.1491, 0.6657, 0.9300]])
tensor([0.1491, 0.6657, 0.9300])
tensor(0.6657)


In [78]:
double_points = torch.rand(2,3,dtype=torch.double)
print(double_points)
short_points = torch.tensor([[1,2],[3,4]],dtype=torch.short)
print(short_points)

tensor([[0.9864, 0.8603, 0.5565],
        [0.5434, 0.3595, 0.5482]], dtype=torch.float64)
tensor([[1, 2],
        [3, 4]], dtype=torch.int16)


In [79]:
double_points = torch.rand(2,2).double()
print(double_points)

tensor([[0.9541, 0.3690],
        [0.9069, 0.3532]], dtype=torch.float64)


In [80]:
double_points = torch.randn(2,2).to(torch.double)
print(double_points)

tensor([[-0.2769,  0.8787],
        [-1.0048, -0.7143]], dtype=torch.float64)


In [81]:
points = torch.randn(2,2)
double_points = points.type(torch.double)
print(double_points)

tensor([[ 0.4567,  0.9987],
        [-1.6742, -0.8038]], dtype=torch.float64)


In [84]:
some_list = list(range(6))
print(some_list[:])
print(some_list[1:])
print(some_list[1:4])
print(some_list[1:4:2])

[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3]
[1, 3]


In [85]:
print(points)

tensor([[ 0.4567,  0.9987],
        [-1.6742, -0.8038]])


In [94]:
points = torch.randn(3,3)
print(points[:])
print(points[1:])
print(points[1:, :])
print(points[:-1])
print(points[1:, 0])

tensor([[-0.9563, -0.8264,  0.1526],
        [-0.0796, -1.7402, -0.2091],
        [ 0.0697, -0.3418, -1.9544]])
tensor([[-0.0796, -1.7402, -0.2091],
        [ 0.0697, -0.3418, -1.9544]])
tensor([[-0.0796, -1.7402, -0.2091],
        [ 0.0697, -0.3418, -1.9544]])
tensor([[-0.9563, -0.8264,  0.1526],
        [-0.0796, -1.7402, -0.2091]])
tensor([-0.0796,  0.0697])


In [104]:
points = torch.rand(2,3).type(torch.double)
points_np = points.numpy()
print(points)
print(points_np)
points.to(device)

tensor([[0.1492, 0.7601, 0.5650],
        [0.2262, 0.6566, 0.4233]], dtype=torch.float64)
[[0.14924914 0.76010579 0.56502622]
 [0.22619689 0.65656269 0.42328149]]


tensor([[0.1492, 0.7601, 0.5650],
        [0.2262, 0.6566, 0.4233]], device='cuda:0', dtype=torch.float64)