In [1]:
import torch

# <a href="https://www.cnblogs.com/flix/p/11262606.html">torch.sum() 和 dim维度</a>

In [9]:
a = torch.randn(3,3,3).type(torch.int)
print(a)
print(torch.sum(a,dim=0))
print(torch.sum(a,dim=1))
print(torch.sum(a,dim=2))
print(torch.sum(a,dim=2,keepdim=True))

tensor([[[ 0,  0,  0],
         [-1,  0,  0],
         [ 1,  0,  0]],

        [[ 2,  0,  0],
         [ 0,  0,  0],
         [ 0, -1,  0]],

        [[ 0,  1,  0],
         [-1,  0,  0],
         [ 0,  1, -1]]], dtype=torch.int32)
tensor([[ 2,  1,  0],
        [-2,  0,  0],
        [ 1,  0, -1]])
tensor([[ 0,  0,  0],
        [ 2, -1,  0],
        [-1,  2, -1]])
tensor([[ 0, -1,  1],
        [ 2,  0, -1],
        [ 1, -1,  0]])
tensor([[[ 0],
         [-1],
         [ 1]],

        [[ 2],
         [ 0],
         [-1]],

        [[ 1],
         [-1],
         [ 0]]])


# <a href="https://blog.csdn.net/zhanly19/article/details/96428781#:~:text=torch.ca,%E6%8E%A5%EF%BC%8C%E8%81%94%E7%B3%BB%E5%9C%A8%E4%B8%80%E8%B5%B7%E3%80%82">torch.cat()</a>

torch.cat是将两个张量（tensor）拼接在一起，cat是concatnate的意思，即拼接，联系在一起。

In [18]:
a = torch.randn(2,3)
b = torch.ones(4,3)
c = torch.zeros(2,4)
print(a)
print(b)
print(c)

tensor([[-0.1660, -0.8532, -0.9135],
        [ 0.5546, -0.6163, -0.6082]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [22]:
d1 = torch.cat((a,b),dim=0)
d2 = torch.cat((a,c),dim=1)
print(d1)
print(d2)
print(d1.shape)
print(d2.shape)

tensor([[-0.1660, -0.8532, -0.9135],
        [ 0.5546, -0.6163, -0.6082],
        [ 1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000]])
tensor([[-0.1660, -0.8532, -0.9135,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.5546, -0.6163, -0.6082,  0.0000,  0.0000,  0.0000,  0.0000]])
torch.Size([6, 3])
torch.Size([2, 7])


# torch.chunk(tensor, chunk_num, dim)

torch.chunk(tensor, chunk_num, dim)与torch.cat()原理相反，它是将tensor按dim（行或列）分割成chunk_num个tensor块，返回的是一个元组。

In [23]:
a = torch.randn(4,5)
print(a)

tensor([[-1.4541,  0.5118,  0.1173,  0.9414,  1.7789],
        [-0.9237,  0.9312,  1.0057,  0.4389,  0.7286],
        [-1.2944,  1.1962,  0.9248,  1.5500, -2.3437],
        [-1.5479,  0.0630, -0.6642, -0.0241, -0.2590]])


In [25]:
c = torch.chunk(input=a, chunks=2, dim=0)
print(c[1])

tensor([[-1.2944,  1.1962,  0.9248,  1.5500, -2.3437],
        [-1.5479,  0.0630, -0.6642, -0.0241, -0.2590]])


# torch.einsum

In [37]:
a = torch.ones(2,3)
print(a)
b = torch.einsum("ij->ji",a)
print(b)
c = torch.einsum("ij->i",a)
print(c)
d = torch.einsum("ik,jk->ij",a,a)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([3., 3.])
tensor([[3., 3.],
        [3., 3.]])
