# Argparse

In [5]:
import argparse
parser = argparse.ArgumentParser(description="测试")

parser.add_argument("--in_channels", type=int, default=3, help="输入通道数")
parser.add_argument("--expect_result", type=float, default=3.0, help="期望结果")
args = parser.parse_args()
print(args.in_channels)
print(args.expect_result)

usage: ipykernel_launcher.py [-h] [--in_channels IN_CHANNELS]
                             [--expect_result EXPECT_RESULT]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\liyingda\AppData\Roaming\jupyter\runtime\kernel-82292e25-0fe4-42f5-8fe9-b50e92c27285.json


SystemExit: 2

# Numpy
## numpy, tensor, cuda, cpu转换

In [12]:
import numpy as np
import torch
import torch.nn as nn
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
a = np.array([2,3,4])
print(a)
print(torch.tensor(a))
print(torch.tensor(a).to(device))
print(torch.tensor(a).cuda())
print(torch.tensor(a).to(device).cpu())

[2 3 4]
tensor([2, 3, 4], dtype=torch.int32)
tensor([2, 3, 4], device='cuda:0', dtype=torch.int32)
tensor([2, 3, 4], device='cuda:0', dtype=torch.int32)
tensor([2, 3, 4], dtype=torch.int32)


In [18]:
b = [2,3,4]
b1 = np.array(b)
b2 = torch.tensor(b)
b3 = torch.tensor(b1)

b4 = b2.numpy()
b5 = b3.numpy()
b6 = np.array(b2)

print(b)

print(b1)
print(b2)
print(b3)

print(b4)
print(b5)
print(b6)

[2, 3, 4]
[2 3 4]
tensor([2, 3, 4])
tensor([2, 3, 4], dtype=torch.int32)
[2 3 4]
[2 3 4]
[2 3 4]


In [37]:
c = [1,2,3]
print(c)

"定义numpy"
print("1. =========================================")
c1 = np.array(c)
print("numpy", c1)

"定义tensor"
print("2. =========================================")
c2 = torch.tensor(c)
print("tensor", c2)

"数据放在cuda上"
print("3. =========================================")
c3 = c2.to(device)
print("cuda", c3)
c3 = c2.cuda()
print("cuda", c3)

"tensor -> numpy"
print("4. =========================================")
c4 = c2.numpy()
print(c4)
c4 = np.array(c2)
print(c4)
c4 = np.array(c3.cpu())
print(c4)

"numpy -> tensor"
print("5. =========================================")
c5 = torch.tensor(c4)
print(c5)

"Cuda转成Numpy ==> 转换为cpu中再转换为numpy"
print("6. =========================================")
c6 = c3.cpu().numpy()
print(c6)

[1, 2, 3]
1. =========================================
numpy [1 2 3]
2. =========================================
tensor tensor([1, 2, 3])
3. =========================================
cuda tensor([1, 2, 3], device='cuda:0')
cuda tensor([1, 2, 3], device='cuda:0')
4. =========================================
[1 2 3]
[1 2 3]
[1 2 3]
5. =========================================
tensor([1, 2, 3])
6. =========================================
[1 2 3]


## numpy基本操作

In [53]:
import numpy as np
d1 = np.zeros(shape=(2,3))
d2 = np.ones(shape=(2,2))
d3 = np.array([[2,3],[3,4]], dtype=int)
d4 = np.empty(shape=(2,10))
print(d1)
print(d2)
print(d3)
print(d4)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[2 3]
 [3 4]]
[[5.26354425e-315 8.50985311e-312 4.94065646e-324 0.00000000e+000
  0.00000000e+000 0.00000000e+000 3.45845952e-323 3.95252517e-323
  5.26354425e-315 8.50985312e-312]
 [4.94065646e-324 0.00000000e+000 0.00000000e+000 0.00000000e+000
  3.45845952e-323 3.95252517e-323 0.00000000e+000 0.00000000e+000
  0.00000000e+000 4.94065646e-324]]


In [70]:
d5 = np.random.random((3,4))
d6 = np.random.rand(2,2)
d7 = np.random.randn(2,2)
d8 = np.random.randint(2,5,size=(2,3))
print(d5)
print(d6)
print(d7)
print(d8)

[[0.51290106 0.88719962 0.20940912 0.23657269]
 [0.68379249 0.86215535 0.04740442 0.9900932 ]
 [0.45628228 0.81428596 0.34215373 0.02693641]]
[[0.4771609  0.49437108]
 [0.66119993 0.3937697 ]]
[[-0.01449782 -0.30285786]
 [-1.26352175 -1.05793095]]
[[3 4 4]
 [2 4 3]]


In [78]:
e1 = np.arange(2,10,2)
e2 = np.arange(2,10,1)

# 创建线段型数据
e3= np.linspace(1,10,20) # 开始端1，结束端10，且分割成20个数据，生成线段print(e1)
print(e2)
print(e3)

[2 3 4 5 6 7 8 9]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [91]:
import numpy as np
a1 = np.random.randint(2,10,8)
a2 = np.random.randint(2,10,8)
print(a1)
print(a2)

a3 = np.array([a1,a2])
a4 = a1.reshape((2,4))
print(a3)
print(a4)

[7 2 9 7 6 9 3 4]
[3 4 4 9 6 2 9 3]
[[7 2 9 7 6 9 3 4]
 [3 4 4 9 6 2 9 3]]
[[7 2 9 7]
 [6 9 3 4]]


In [92]:
"数组转置"
a = np.random.randint(1,10,(2,4))
b = a.T
print(a)
print(b)

[[4 7 7 2]
 [4 7 1 3]]
[[4 4]
 [7 7]
 [7 1]
 [2 3]]


In [101]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[1,2,3]])
print(a.ndim)
print(b.ndim)
print(a.shape)
print(b.shape)
print(a.size) # 元素个数
print(b.size)
print(a.dtype) # 元素类型
print(np.random.randint(1,10,(4,)))

1
2
(3,)
(2, 3)
3
6
int32
[3 4 7 2]


In [105]:
"数组的运算"
a1 = np.zeros((3,))
a2 = np.ones((3,))
a3 = np.random.random(size=(3,))
print(a1+a2)
print(a1+a2+a3)

[1. 1. 1.]
[1.47274973 1.72300539 1.74211524]


In [112]:
a1 = np.ones((3,))
a1[0] = 0
print(a1)
a2 = np.array([1,2,3])
print(a2)
print(a1*a2)
print(a1@a2)

[0. 1. 1.]
[1 2 3]
[0. 2. 3.]
5.0


In [125]:
a = np.random.randint(1,5,size=(3,))
print(a)
print(np.mean(a))
print(np.max(a))
print(np.median(a))
print(np.prod(a))
print(np.cumsum(a))  ## [1,3,2] => [1,1+3,1+3+2] => [1,4,6]

[3 1 2]
2.0
3
2.0
6
[3 4 6]


In [124]:
""""
计算数组的标准差
numpy.std(arr, axis=None, dtype=None, out=None): 计算数组的标准差。参数axis、dtype和out的含义与numpy.mean()相同。

计算数组的方差
numpy.var(arr, axis=None, dtype=None, out=None): 计算数组的方差。参数axis、dtype和out的含义与numpy.mean()相同。

 计算数组的最小值
numpy.min(arr, axis=None, out=None): 计算数组的最小值。参数axis和out的含义与numpy.mean()相同。

 计算数组的最大值
numpy.max(arr, axis=None, out=None): 计算数组的最大值。参数axis和out的含义与numpy.mean()相同

计算数组的元素之和
numpy.sum(arr, axis=None, dtype=None, out=None): 计算数组的元素之和。参数axis、dtype和out的含义与numpy.mean()相同。

计算数组的元素乘积
numpy.prod(arr, axis=None, dtype=None, out=None): 计算数组的元素乘积。参数axis、dtype和out的含义与numpy.mean()相同

计算数组的累积和
numpy.cumsum(arr, axis=None, dtype=None, out=None): 计算数组的累积和。参数axis、dtype和out的含义与numpy.mean()相同。
"""

'"\n计算数组的标准差\nnumpy.std(arr, axis=None, dtype=None, out=None): 计算数组的标准差。参数axis、dtype和out的含义与numpy.mean()相同。\n\n计算数组的方差\nnumpy.var(arr, axis=None, dtype=None, out=None): 计算数组的方差。参数axis、dtype和out的含义与numpy.mean()相同。\n\n 计算数组的最小值\nnumpy.min(arr, axis=None, out=None): 计算数组的最小值。参数axis和out的含义与numpy.mean()相同。\n\n 计算数组的最大值\nnumpy.max(arr, axis=None, out=None): 计算数组的最大值。参数axis和out的含义与numpy.mean()相同\n\n计算数组的元素之和\nnumpy.sum(arr, axis=None, dtype=None, out=None): 计算数组的元素之和。参数axis、dtype和out的含义与numpy.mean()相同。\n\n计算数组的元素乘积\nnumpy.prod(arr, axis=None, dtype=None, out=None): 计算数组的元素乘积。参数axis、dtype和out的含义与numpy.mean()相同\n\n计算数组的累积和\nnumpy.cumsum(arr, axis=None, dtype=None, out=None): 计算数组的累积和。参数axis、dtype和out的含义与numpy.mean()相同。\n'

In [129]:
"数组的索引和切片"
a = np.random.randint(1,10,size=(8,))
print(a)
print(a[1:])
print(a[:2])

[7 4 2 4 6 5 5 3]
[4 2 4 6 5 5 3]
[7 4]


In [138]:
b = np.random.randint(1,10,size=(2,2,3))
print(b)
"行切片"
print(b[0:1])
print(b[0:1,0:1])
print(b[0:1,0:1,0:1].reshape((1,1,)))


[[[1 7 8]
  [8 3 1]]

 [[4 1 7]
  [6 1 8]]]
[[[1 7 8]
  [8 3 1]]]
[[[1 7 8]]]
[[1]]


In [146]:
"列切片"
a = np.random.randint(1,10,size=(2,2,8))
print(a)
print(a[:,])
print(a[:,:,0:1])

[[[8 4 1 9 9 5 4 8]
  [3 8 5 6 8 6 1 6]]

 [[3 1 3 7 8 9 2 2]
  [5 7 8 4 2 4 5 8]]]
[[[8 4 1 9 9 5 4 8]
  [3 8 5 6 8 6 1 6]]

 [[3 1 3 7 8 9 2 2]
  [5 7 8 4 2 4 5 8]]]
[[[8]
  [3]]

 [[3]
  [5]]]


In [155]:
"数组堆叠"
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.vstack((a1, a2)))
print(np.hstack((a1, a2)))
print(a3)
print(np.vsplit(a3,3))
print(np.hsplit(a3, 3))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [ ]:
"""
# 保存数组到文件
np.save('my_array.npy', data)

# 加载数组
loaded_data = np.load('my_array.npy')
"""