In [7]:
import torch
import torchvision.models as models
import torch.nn as nn

gru = nn.GRUCell(input_size=2, hidden_size=64)
lin = nn.Linear(in_features=64, out_features=2)
data_input = torch.rand((2,))
print(data_input)
y = gru(data_input)
print(y)
y = lin(y)
print(y)

tensor([0.2883, 0.3497])
tensor([ 0.0528, -0.0210,  0.0475, -0.0056,  0.0043, -0.0056,  0.0029,  0.0210,
         0.0865,  0.0750,  0.0435, -0.0126,  0.0232, -0.0656,  0.0388,  0.0461,
         0.0609, -0.0706,  0.0591,  0.0031,  0.0354, -0.0068,  0.0209, -0.0132,
         0.0073, -0.0353,  0.0226, -0.0101, -0.0477, -0.0440, -0.0018,  0.0143,
         0.0010, -0.0394,  0.0205,  0.0480,  0.0367, -0.0245, -0.0066, -0.0334,
        -0.0211,  0.0208, -0.0220, -0.0329,  0.0160,  0.0582,  0.0590, -0.0370,
        -0.0335,  0.0192,  0.0763, -0.0693, -0.0145,  0.0196,  0.0714, -0.0198,
         0.0607, -0.0356,  0.0227, -0.0821, -0.0171,  0.0633,  0.0283, -0.0285],
       grad_fn=<SqueezeBackward1>)
tensor([-0.0028,  0.0649], grad_fn=<AddBackward0>)


tensor([0.3609, 0.0366], grad_fn=<SqueezeBackward1>)
